# Test 분류

In [20]:
import matplotlib as plt
import pandas as pd

# CSV 불러오기
df = pd.read_csv("test_prediction_results.csv") 

# 실제 라벨별로 예측 결과 분포 구하기 (그룹화)
grouped = df.groupby(["true_label", "predicted_label"]).size().unstack(fill_value=0)
print("실제 라벨별 예측 결과 분포:")
grouped

실제 라벨별 예측 결과 분포:

predicted_label  contempt  disgust  happy  neutral  sad  surprise
true_label
anger                   1        7      3      204    2        83
happy                   4        1    185       75    0        35
panic                   0        0      6      109    0       185
sadness                 1        5     10      251    6        27

In [21]:
# ② 틀린 예측만 필터링
wrong_preds = df[df["true_label"] != df["predicted_label"]]

# 실제 라벨별로 틀린 예측의 분포
wrong_grouped = wrong_preds.groupby(["true_label", "predicted_label"]).size().unstack(fill_value=0)
print("\n틀린 예측 시, 예측된 라벨 분포:")
wrong_grouped

틀린 예측 시, 예측된 라벨 분포:

predicted_label  contempt  disgust  happy  neutral  sad  surprise
true_label
anger                   1        7      3      204    2        83
happy                   4        1      0       75    0        35
panic                   0        0      6      109    0       185
sadness                 1        5     10      251    6        27

In [22]:
# 필요 시 비율(%)로 변환
wrong_grouped_percent = wrong_grouped.div(wrong_grouped.sum(axis=1), axis=0) * 100
print("\n틀린 예측 분포(백분율):")
wrong_grouped_percent.round(1)

틀린 예측 분포(백분율):

predicted_label  contempt  disgust  happy  neutral  sad  surprise
true_label
anger                 0.3      2.3    1.0     68.0  0.7      27.7
happy                 3.5      0.9    0.0     65.2  0.0      30.4
panic                 0.0      0.0    2.0     36.3  0.0      61.7
sadness               0.3      1.7    3.3     83.7  2.0       9.0

# Train 분류

In [7]:
import pandas as pd

# CSV 불러오기
df = pd.read_csv("train_prediction_results.csv") 

# 실제 라벨별로 예측 결과 분포 구하기 (그룹화)
grouped = df.groupby(["true_label", "predicted_label"]).size().unstack(fill_value=0)

In [13]:
print("실제 라벨별 예측 결과 분포:")
grouped

실제 라벨별 예측 결과 분포:

predicted_label,anger,contempt,disgust,happy,neutral,panic,sad,surprise
true_label,,,,,,,,
anger,4,2,37,72,944,3,6,432
happy,0,16,1,930,385,0,1,157
panic,0,1,2,22,597,3,1,875
sadness,1,1,23,35,1305,3,29,103

In [10]:
# ② 틀린 예측만 필터링
wrong_preds = df[df["true_label"] != df["predicted_label"]]

# 실제 라벨별로 틀린 예측의 분포
wrong_grouped = wrong_preds.groupby(["true_label", "predicted_label"]).size().unstack(fill_value=0)

In [12]:
print("\n틀린 예측 시, 예측된 라벨 분포:")
wrong_grouped

틀린 예측 시, 예측된 라벨 분포:

predicted_label,anger,contempt,disgust,happy,neutral,panic,sad,surprise
true_label,,,,,,,,
anger,0,2,37,72,944,3,6,432
happy,0,16,1,0,385,0,1,157
panic,0,1,2,22,597,0,1,875
sadness,1,1,23,35,1305,3,29,103

In [14]:
# 필요 시 비율(%)로 변환
wrong_grouped_percent = wrong_grouped.div(wrong_grouped.sum(axis=1), axis=0) * 100

In [15]:
print("\n틀린 예측 분포(백분율):")
wrong_grouped_percent.round(1)

틀린 예측 분포(백분율):

predicted_label,anger,contempt,disgust,happy,neutral,panic,sad,surprise
true_label,,,,,,,,
anger,0.0,0.1,2.5,4.8,63.1,0.2,0.4,28.9
happy,0.0,2.9,0.2,0.0,68.8,0.0,0.2,28.0
panic,0.0,0.1,0.1,1.5,39.9,0.0,0.1,58.4
sadness,0.1,0.1,1.5,2.3,87.0,0.2,1.9,6.9

# Val 분류

In [6]:
import pandas as pd

# CSV 불러오기
df = pd.read_csv("val_prediction_results.csv") 

# 실제 라벨별로 예측 결과 분포 구하기 (그룹화)
grouped = df.groupby(["true_label", "predicted_label"]).size().unstack(fill_value=0)
print("실제 라벨별 예측 결과 분포:")
print(grouped)

# ② 틀린 예측만 필터링
wrong_preds = df[df["true_label"] != df["predicted_label"]]

# 실제 라벨별로 틀린 예측의 분포
wrong_grouped = wrong_preds.groupby(["true_label", "predicted_label"]).size().unstack(fill_value=0)
print("\n틀린 예측 시, 예측된 라벨 분포:")
print(wrong_grouped)

# 필요 시 비율(%)로 변환
wrong_grouped_percent = wrong_grouped.div(wrong_grouped.sum(axis=1), axis=0) * 100
print("\n틀린 예측 분포(백분율):")
print(wrong_grouped_percent.round(1))

실제 라벨별 예측 결과 분포:
predicted_label  contempt  disgust  happy  neutral  sad  surprise
true_label
anger                   0        2      9      206    1        82
happy                   6        0    191       82    0        21
panic                   0        0      1      111    0       188
sadness                 0        2      8      260   10        20

틀린 예측 시, 예측된 라벨 분포:
predicted_label  contempt  disgust  happy  neutral  sad  surprise
true_label
anger                   0        2      9      206    1        82
happy                   6        0      0       82    0        21
panic                   0        0      1      111    0       188
sadness                 0        2      8      260   10        20

틀린 예측 분포(백분율):
predicted_label  contempt  disgust  happy  neutral  sad  surprise
true_label
anger                 0.0      0.7    3.0     68.7  0.3      27.3
happy                 5.5      0.0    0.0     75.2  0.0      19.3
panic                 0.0      0.0    0.3     37.0  0.0      62.7
sadness               0.0      0.7    2.7     86.7  3.3       6.7